### PR TITLE
Miscellaneous Fixes

### LINKED ISSUE #166: Serial Disconnect and Reconnect Crashes Application
Currently, a user cannot cleanly disconnect from a serial device then reconnect to the same device without a `tauri::async_runtime::thread` error being thrown.

### LINKED ISSUE #282: Don't show nodes on map unless GPS lock acquired
Currently, nodes are shown at (0, 0) when their GPS isn't initialized or isn't active. Don't show devices' locations that aren't valid locations.

### LINKED ISSUE #284: Save map view location across tab views
Currently, the map view resets its zoom and position when the tab is deselected and reselected. This state needs to be held across tab views.

### LINKED ISSUE #292: Development server doesn't disconnect from device on UI reload
The development server doesn't disconnect from a device on reload, meaning the application either has to be restarted or the device has to be unplugged when developing the UI and making high-level UI changes.

### LINKED ISSUE #295: Bug: MyNodeInfo does not exist on type Meshdevice
In meshtastic-emergency-response-client/src/features/device/deviceSelectors.ts /
https://github.com/ajmcquilkin/meshtastic-emergency-response-client/blob/4b106d76bab336f20982f911039b3da165bc2933/src/features/device/deviceSelectors.ts#L23

Error: MyNodeInfo does not exist on type.

Error blocking build.

image

### PR DESCRIPTION
**Pull request by ajmcquilkin**
This PR fixes many small but annoying issues within the application, listed below:

- #166 
- #282 
- #284 
- #292 
- #295 
- Show all channels on channel config page
- Allow for toggling selected node in map view
- Decreased legend text size
- Showed location instead of MAC addr for nodes

Closes #166
Closes #282 
Closes #284 
Closes #292
Closes #295

### CODE REVIEW

File: src/components/NodeSearch/NodeSearchResult.tsx [hunk 1]
```diff
@@ -75,8 +75,13 @@ const NodeSearchResult = ({
...
           </span>
         </p>
-        {/* <p>{Buffer.from(node.data.user?.macaddr ?? []).toString('hex')}</p> */}
-        <p className="text-sm font-light">demo mac address</p>
+        <p className="text-sm font-light">
+          {!!node.data.position?.latitudeI && !!node.data.position?.longitudeI
+            ? `${node.data.position.latitudeI / 1e7}, ${
+                node.data.position.longitudeI / 1e7
+              }`
+            : "No position lock, not displaying"}
```
Comment (sherry1iu) [inline src/components/NodeSearch/NodeSearchResult.tsx:83]: Nit: Something like "No location detected" is a little easier to read

**Review by sherry1iu — APPROVED** [review]
Looks good!

**Review by sherry1iu — APPROVED** [review]
Looks good!
